In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [10]:
import sys
sys.path.append('/Users/guydavidson/projects/simple-relational-reasoning/')

import torch

In [11]:
from simple_relational_reasoning.datagen import object_fields
from simple_relational_reasoning.datagen import object_gen

In [80]:
cfgs = ( 
    object_gen.FieldConfig('x', 'int_position', tuple()), 
    object_gen.FieldConfig('y', 'int_position', tuple()), 
    object_gen.FieldConfig('color', 'one_hot', (4,))
)

gen = object_gen.ObjectGenerator(10, cfgs, object_gen.adjacent_relation_evaluator)
gen()

(tensor([[[8, 5, 1, 0, 0, 0],
          [5, 3, 0, 1, 0, 0],
          [9, 5, 0, 0, 1, 0],
          [8, 5, 1, 0, 0, 0],
          [2, 3, 1, 0, 0, 0],
          [7, 5, 0, 1, 0, 0],
          [2, 7, 0, 0, 0, 1],
          [6, 4, 0, 0, 1, 0],
          [4, 0, 0, 0, 0, 1],
          [9, 1, 0, 0, 0, 1]]], dtype=torch.int32), tensor([True]))

In [71]:
x = [g() for g in gen.field_generators.values()]
[y.shape for y in x]

[torch.Size([4, 1]), torch.Size([4, 1]), torch.Size([4, 4])]

In [18]:
torch.cat(x, dim=1)

tensor([[6, 3, 0, 1, 0, 0],
        [1, 8, 0, 0, 1, 0],
        [7, 9, 0, 1, 0, 0],
        [6, 7, 0, 0, 1, 0],
        [9, 5, 1, 0, 0, 0],
        [8, 8, 1, 0, 0, 0],
        [3, 6, 0, 1, 0, 0],
        [3, 3, 0, 0, 1, 0],
        [2, 4, 0, 1, 0, 0],
        [0, 7, 0, 1, 0, 0]], dtype=torch.int32)

In [32]:
batch_size = 1
z = [[torch.cat([g() for g in gen.field_generators.values()], dim=1)
                         for _ in range(gen.n)]
                        for _ in range(batch_size)]

In [39]:
torch.stack(z[0]).shape

torch.Size([10, 10, 6])

In [30]:
torch.tensor(z)

ValueError: only one element tensors can be converted to Python scalars

In [31]:
len(z), len(z[0])

2

In [56]:
torch.any(torch.isclose(torch.tensor([1]), torch.arange(10)))

tensor(True)

In [52]:
torch.cdist?

Docstring:
cdist(x1, x2, p=2) -> Tensor

Computes the p-norm distance between each pair of the two collections of row vectors.

If x1 has shape :math:`P \times M` and x2 has shape :math:`R \times M` then the 
output will have shape :math:`P \times R`.

This function is equivalent to `scipy.spatial.distance.cdist(input,'minkowski', p=p)` 
if :math:`p \in (0, \infty)`. When :math:`p = 0` it is equivalent to 
`scipy.spatial.distance.cdist(input, 'hamming') * M`. When :math:`p = \infty`, the closest 
scipy function is `scipy.spatial.distance.cdist(xn, lambda x, y: np.abs(x - y).max())`.

Args:
    x1 (Tensor): input tensor of shape :math:`P \times M`.
    x2 (Tensor): input tensor of shape :math:`R \times M`.
    p: p value for the p-norm distance to calculate between each vector pair
        :math:`\in [0, \infty]`.

Example::

    >>> a = torch.tensor([[0.9041,  0.0196], [-0.3108, -2.4423], [-0.4821,  1.059]])
    >>> a
    tensor([[ 0.9041,  0.0196],
            [-0.3108, -2.4423],
    